- tools/dvrescue.xsd
Validates, although may not contain all permutations, and could be more strict in places
> create flexible validator

- tools/dvrescue.xsd
(Nevermind I answered my own question here)
> Add enumerations to restricted attr fields

- .travis.yml
- Source/Common/ProcessFile.cpp
- Source/Common/ProcessFile.h
- Source/Common/XmlOutput.cpp
Parsing MediaInfo DV event error messages
Display per frame and per Dseq
New MediaInfo is needed (https://github.com/MediaArea/MediaInfoLib/pull/1185).
> Parsing MediaInfo DV event error messages

- README.md
Just enough to gets folks started. :)
> Add some documentation to README

- Project/GNU/CLI/Makefile.am
- Project/GNU/dvrescue.spec
- Project/Mac/mkdmg.sh
- debian/dvrescue.install
Install tools as the same time as dvrescue binary.
> Install tools

- LICENSE
This is regarding #10. 
@JeromeMartinez proposed BSD-2, Andrew (representing MIPoPS) prefers BSD-3. Feel free to discuss in the original issue, above.
> Switch to permanent license

- .appveyor.yml
This adds automatic compilation of the tool for Windows.
(Compilation for macOS and Linux are already handled by Travis)
> Enable AppVeyor

- Source/CLI/CLI_Help.cpp
- Source/CLI/CLI_Main.cpp
- Source/CLI/CommandLine_Parser.cpp
Fix #11 and related other issues.
> Command line parser fixes

- tools/dvrescue.xsd
> Remove sct

- Source/Common/XmlOutput.cpp
> Fix frames closing XML element sometimes missing

- README.md
> Articulate install links

- Source/Common/Output.cpp
- Source/Common/Output.h
> PTS rounding digit count is tweakable

- Source/Common/Output_Xml.cpp
Revert of https://github.com/mipops/dvrescue/pull/48#issuecomment-613752974 ;-).
> XML PTS count of digits after comma is 6

- Source/Common/Output.cpp
- Source/Common/Output.h
- Source/Common/Output_Webvtt.cpp
> WebVTT timestamp rounding down to the nearest

- Source/CLI/CommandLine_Parser.cpp
- Source/Common/Output.h
Fix https://github.com/mipops/dvrescue/issues/50#issuecomment-617300967 (mainly \@tc_nc, \@rdt_nc, \@arb_r)
> Fix regression during previous refactoring

- Project/Mac/mkdmg.sh
> Enable notarization of macOS binaries

- Project/Mac/mkdmg.sh
> Sign avfctl binary

- tools/avfctl/avfctl.m
- tools/avfctl/main.m
- fix #73 (Add help)
- fix #71 (Allow to change output file)
- fix #72 (Use device "0" if not specified)
> Rework command line of avfctl tool

- Source/Common/Output_Webvtt.cpp
- Source/Common/Output_Xml.cpp
Don't expect anymore that error related pointers actually have errors.
This should not happen because error related pointers are usually created only if there are really errors, but better to have good formatting even if this is not the case.
Fix https://github.com/mipops/dvrescue/issues/82 by outputting a valid output, but with wrong info (no audio error displayed but there are audio errors), "real" fix is https://github.com/MediaArea/MediaInfoLib/pull/1253.
> Fix output formatting errors in corner cases

- Project/GNU/dvrescue.spec
> Fix Mageia OBS build

- Source/Common/Output_Xml.cpp
> Add info about not DV in XML output

- Project/GNU/PKGBUILD
- Project/GNU/dvrescue.spec
- debian/control
> Add xmlstarlet to dependencies

- Source/Common/Output_Xml.cpp
- tools/dvrescue.xsd
> Position (byte offset) of the first frame of the current frames sequence

- tools/avfctl/avfctl.h
- tools/avfctl/avfctl.m
- tools/avfctl/main.m
> avfctl: add -foreground and -status options

- Source/Common/Output_Xml.cpp
- tools/dvrescue.xsd
Fix https://github.com/mipops/dvrescue/issues/114.
> More media attributes

- tools/avfctl/Makefile
- tools/avfctl/main.m
> avfctl: Try to probe more device info from driver

- Source/Common/Output.h
- Source/Common/Output_Xml.cpp
- tools/dvrescue.xsd
> Add pack and conceal flags, hides details if frame is concealed

- tools/dvplay
Should resolve https://github.com/mipops/dvrescue/issues/138
> add option for user selected output directory

- tools/dvpackager
- tools/dvplay
- tools/dvsampler
* Adds missing function to scripts that call `_report`
* Fixes project url in `dvsampler`
> Add missing function

- tools/dvrescue.xsd
Adds some attributes into xsd file
> Add to xsd

- tools/dvpackager
- tools/dvplay
* Font path for Ubuntu
* Missing date function
* Usage/help function
Addresses https://github.com/mipops/dvrescue/issues/142
Suggested changes to wordings welcome!
> Add usage function

- tools/dvplay
Should fix https://github.com/mipops/dvrescue/issues/147
> add -nostdin

- tools/dvloupe
- tools/dvplay
Fixes some tools not exiting on bad option
> correct exit action

- docs/_sections/glossary.md
Still a WIP but we can make it available in the meantime!
> Docs: Add initial draft of glossary

- Source/Common/Output_Xml.cpp
Update of https://github.com/mipops/dvrescue/pull/170.
> Option for ignoring caption presence change, update

- Source/Common/Merge.cpp
Fix https://github.com/mipops/dvrescue/issues/179
> Fix wrong frame status init

- .github/workflows/dvrescue-gui.yml
- Source/GUI/dvrescue/dvrescue/PlotPicker.qml
- Source/GUI/dvrescue/dvrescue/main.qml
- Source/GUI/dvrescue/dvrescue/qwtquick2plot.cpp
- Source/GUI/dvrescue/dvrescue/qwtquick2plot.h
implement custom zooming via shift-&-select
introduce ability to scroll plot with right-press & mouse move
> zooming & scrolling

- Source/CLI/CommandLine_Parser.cpp
- Source/Common/Merge.cpp
Also do not repeat the previous frame when there are a gap in the time code.
> Rework of merge algorithm and stats

- tools/avfctl/Makefile
> Handle environment in avfctl Makefile

- Source/CLI/CLI_Help.cpp
- Source/CLI/CommandLine_Parser.cpp
- Source/Common/Merge.cpp
- Source/Common/Merge.h
- Source/Common/ProcessFile.cpp
- Source/Common/ProcessFile.h
as well as streams with repeated frames and with first frames not having any time code.
Fix https://github.com/mipops/dvrescue/issues/189.
Fix https://github.com/mipops/dvrescue/issues/190.
Fix https://github.com/mipops/dvrescue/issues/175.
> Merge: handle non synchronized streams

- Source/Common/Output_Xml.cpp
Fix https://github.com/mipops/dvrescue/issues/208.
Fix https://github.com/mipops/dvrescue/issues/188.
> Fix XML output when full_conceal_vid is set without full_conceal set

- tools/dvgraph
The options don't yet work, but this is run like `./dvgraph dvrescue.xml` and outputs a sidecar jpg using gnuplot. Have fun @bturkus.
> dvgraph: initial commit

- tools/dvplay
fixes https://github.com/mipops/dvrescue/issues/200
> Dvplay play

- Source/GUI/dvrescue/dvrescue/AnalysePage.qml
- Source/GUI/dvrescue/dvrescue/DvRescueCLI.qml
- Source/GUI/dvrescue/dvrescue/main.qml
- Source/GUI/dvrescue/dvrescue/qml.qrc
produce scc / vtt / xml on loading video without related xml
note: functionality requires either specifying DVRescue (cli) path explicitly (via settings button) or having DVRescue in $PATH
> Report generation

- .github/workflows/dvrescue-gui.yml
- Source/GUI/dvrescue/dvrescue/AnalysePage.qml
- Source/GUI/dvrescue/dvrescue/DataView.qml
- Source/GUI/dvrescue/dvrescue/PlayerView.qml
- Source/GUI/dvrescue/dvrescue/SortableFiltrableColumnHeading.qml
- Source/GUI/dvrescue/dvrescue/TableViewEx.qml
- Source/GUI/dvrescue/dvrescue/TextDelegate.qml
- Source/GUI/dvrescue/dvrescue/datamodel.cpp
- Source/GUI/dvrescue/dvrescue/datamodel.h
- Source/GUI/dvrescue/dvrescue/qtavplayerutils.cpp
> [WIP] - Tableview

- Source/GUI/dvrescue/dvrescue.pro
- Source/GUI/dvrescue/dvrescue/AnalysePage.qml
- Source/GUI/dvrescue/dvrescue/DataView.qml
- Source/GUI/dvrescue/dvrescue/DvRescueCLI.qml
- Source/GUI/dvrescue/dvrescue/datamodel.cpp
- Source/GUI/dvrescue/dvrescue/launcher.cpp
also build fix for ubuntu 18.04
> Infinite spinner & more table updates

- tools/dvpackager
some fixes thanks to feedback and testing via @cmhosale
> Dvpackager xml update

- tools/dvrescue.xsd
to merge before https://github.com/mipops/dvrescue/pull/242 and document its xml changes.
> Xsd update abst

- Source/GUI/dvrescue/dvrescue/icons/record-marker-start-graph.svg
- Source/GUI/dvrescue/dvrescue/icons/record-marker-stop+start-graph.svg
- Source/GUI/dvrescue/dvrescue/icons/record-marker-stop-graph.svg
Adjusted width for graph marker icons to reduce width (to make them not look so crowded when zoomed out in graph view).
> new graph marker icons

- Source/GUI/dvrescue/dvrescue/PlayerView.qml
- Source/GUI/dvrescue/dvrescue/icons/first-frame.svg
- Source/GUI/dvrescue/dvrescue/icons/last-frame.svg
- Source/GUI/dvrescue/dvrescue/icons/next-frame.svg
- Source/GUI/dvrescue/dvrescue/icons/previous-frame.svg
- Source/GUI/dvrescue/dvrescue/qml.qrc
New navigation icons for previous frame, next frame, last frame and first frame.
> new navigation icons

- Source/GUI/dvrescue/dvrescue/AnalysePage.qml
- Source/GUI/dvrescue/dvrescue/CustomButton.qml
- Source/GUI/dvrescue/dvrescue/FileView.qml
- Source/GUI/dvrescue/dvrescue/PlotsView.qml
- Source/GUI/dvrescue/dvrescue/icons/add-files.svg
- Source/GUI/dvrescue/dvrescue/icons/exit.svg
- Source/GUI/dvrescue/dvrescue/icons/hide-file-list.svg
- Source/GUI/dvrescue/dvrescue/icons/recent.svg
- Source/GUI/dvrescue/dvrescue/icons/show-file-list.svg
- Source/GUI/dvrescue/dvrescue/qml.qrc
New additional icons for buttons: exit, add files, recent, show file list, and hide file list.
> additional icon buttons

- Source/Common/Merge.cpp
abst is displayed ("??????" if different, with list per file at the end of the line).
timecode is with "HH:MM:" part.
Output becomes something like:
```
#|Abst  |HH:MM:SS:FF|U|St|Comments
166     -1 ??:??:??:?? 1 P
167     -1 ??:??:??:?? 1 P
168     -1 ??:??:??:?? X PP,   90    0 block picks & 1350 remaining block errors
169 ?????? 00:00:00:00 X PP,    0 1430 block picks &   10 remaining block errors, abst     -1   2524
170 ?????? 00:00:00:01 1 P , abst     -1   2536
171   2554 00:00:00:02 0  P
172   2565 00:00:00:03 0  M
173   2584 00:00:00:04 X MP,    0 1391 block picks &   49 remaining block errors
```
> Display abst information in the merge output

- .github/workflows/dvrescue-gui.yml
- Source/Common/Output_Xml.cpp
Math is less pure but it permits to avoid to miss the first frame when used with other tools, cc @dericed.
> Change pts rounding in XML to round down

- tools/dvpackager
fixes https://github.com/mipops/dvrescue/issues/330
> check that ffmpeg is installed and stop if not

- tools/dvpackager
resolves https://github.com/mipops/dvrescue/issues/321
> Mono mapping

- Source/Common/Output_Xml.cpp
- Source/Common/ProcessFile.cpp
- Source/Common/ProcessFile.h
- tools/dvrescue.xsd
Fix https://github.com/mipops/dvrescue/issues/329.
> Avoid starting a sequence with no audio pack then audio pack

- Source/GUI/dvrescue/dvrescue/main.cpp
- Source/GUI/dvrescue/dvrescue/main.qml
> Search for tools in application bundle on macOS

- tools/dvpackager
- tools/dvplay
Between dvplay and dvpackager this readjusts the related files. with `dvplay -x` and `dvpackager -S` now the result looks like:
> Xml to dv relationship

- Source/Common/Output.cpp
- Source/Common/Output.h
- Source/Common/Output_Xml.cpp
- Source/Common/ProcessFile.cpp
Fix https://github.com/mipops/dvrescue/issues/94.
Needs https://github.com/MediaArea/MediaInfoLib/pull/1416
> Detail the non-continuity in rdt_nc and tc_nc

- Source/GUI/dvrescue/dvrescue/icons/capture.svg
> GUI - capture icon

- Project/GNU/CLI/Makefile.am
- Project/GNU/CLI/configure.ac
- tools/avfctl/Makefile
> Add compile flags for ObjC(++)

- Source/Common/Merge.cpp
- Source/Common/Output.cpp
- Source/Common/Output.h
- Source/Common/Output_Captions_Scc.cpp
- Source/Common/Output_Xml.cpp
- Source/Common/ProcessFile.cpp
Fix https://github.com/mipops/dvrescue/pull/340#issuecomment-955574373.
Needs https://github.com/MediaArea/MediaInfoLib/pull/1455.
> Detail the non-continuity in rdt_nc and tc_nc, update

- Source/Common/Output_Xml.cpp
- tools/dvrescue.xsd
I suggest to merge after resolving comments at end of https://github.com/mipops/dvrescue/pull/340#issuecomment-955574373.
> Xml to 1.2.1

- Source/GUI/dvrescue/dvrescue/qwtquick2plot.cpp
> Handle qwt versions < 6.2

- Source/GUI/dvrescue/dvrescue/datamodel.cpp
> Fix build with GCC 8.x (Debian 10)

- Source/GUI/dvrescue/dvrescue/main.cpp
> Linux: Search for tools in $prefix/lib{,64}/dvrescue/bin

- Source/Common/Output.cpp
- Source/Common/Output.h
- Source/Common/Output_Xml.cpp
- Source/Common/ProcessFile.cpp
- tools/dvrescue.xsd
Fix https://github.com/mipops/dvrescue/issues/418#issuecomment-1013492433.
Needs https://github.com/MediaArea/MediaInfoLib/pull/1475.
> Consider audio with any value repeated as concealed audio

- tools/dvpackager
Should address an issue with mapping of dual stereo pairs
> mapping for second stereo pair

- Source/GUI/dvrescue/dvrescue/CaptureFrameInfo.qml
> Fix Qt 5.12

- tools/dvpackager
should fix https://github.com/mipops/dvrescue/issues/435
> provide option to force packaged audio to 48kHz

- Source/GUI/dvrescue/dvrescue.qmltests/tests/tst_captureframeinfo.qml
- Source/GUI/dvrescue/dvrescue/CaptureFrameInfo.qml
- Source/GUI/dvrescue/dvrescue/TransferPage.qml
- Source/GUI/dvrescue/dvrescue/csvparser.cpp
> Capture visualization

- Source/GUI/dvrescue/dvrescue.qmltests/tests/tst_captureframeinfo.qml
- Source/GUI/dvrescue/dvrescue.qmltests/tests/tst_dvloupeview.qml
- Source/GUI/dvrescue/dvrescue.qmltests/tests/tst_navbar.qml
- Source/GUI/dvrescue/dvrescue/AnalysePage.qml
- Source/GUI/dvrescue/dvrescue/DvLoupeView.qml
https://github.com/mipops/dvrescue/issues/484
> dvloupe ui: add dif block filter

- .github/workflows/dvrescue-gui.yml
> CI: Fix Qt6 parts

- Source/Common/Merge.cpp
Example:
```
FramePos,abst,abst_r,abst_nc,tc,tc_r,tc_nc,rdt,rdt_r,rdt_nc,rec_start,rec_end,Used,Status,Comments,BlockErrors,IssueFixed,SourceSpeed,FrameSpeed,InputPos,OutputPos
0,917210,,,00:51:00;13,,,,,,,,0,M,,0,0,0.0,32,0|,0
1,917220,,,00:51:00;14,,,,,,,,0,M,,0,0,0.0,32,120000|,120000
2,917230,,,00:51:00;15,,,,,,,,0,,0,0,0.0,32,240000|0,240000
3,917240,,,00:51:00;16,,,,,,,,0,,0,0,0.0,32,360000|120000,360000
```
> Add in/out file offset to CSV output

- Source/Common/Merge.cpp
Fix https://github.com/mipops/dvrescue/issues/513.
> Fix CSV misalignment

- Source/Common/SimulatorWrapper.cpp
e.g. when rewind order, frames are still in forward order, with frame speed info slowing down by 0.1x increment up to reversing the frame order
> Simulator behaves more like real deck

- Source/GUI/dvrescue/dvrescue/AnalysePage.qml
- Source/GUI/dvrescue/dvrescue/PackagePage.qml
- Source/GUI/dvrescue/dvrescue/icons/add-files.svg
- Source/GUI/dvrescue/dvrescue/icons/recent.svg
> GUI: replace "add file" and "recent file" icons #507

- Source/GUI/dvrescue/dvrescue/DvRescueLogo.ui.qml
- Source/GUI/dvrescue/dvrescue/qml.qrc
> use logo-inverse.png

- .github/workflows/DVRescue_Checks.yml
> Update apt cache in ci script

- tools/dvpackager
partially replaces https://github.com/mipops/dvrescue/pull/429
> dvpackager lavf dependency check update

- Source/GUI/dvrescue/dvrescue/AnalyseDataView.qml
- Source/GUI/dvrescue/dvrescue/JumpRepeatTextDelegate.qml
- Source/GUI/dvrescue/dvrescue/SegmentDataView.qml
- Source/GUI/dvrescue/dvrescue/qml.qrc
> use conditional jumpImage icons #526

- Source/GUI/dvrescue/dvrescue/AnalysePage.qml
- Source/GUI/dvrescue/dvrescue/DvLoupeView.qml
- Source/GUI/dvrescue/dvrescue/ResizeHandle.qml
- Source/GUI/dvrescue/dvrescue/ResizeRectangle.qml
- Source/GUI/dvrescue/dvrescue/qml.qrc
> make dvloupe view dialog resizeable

- Source/GUI/dvrescue/dvrescue.tests/xmlparsingtest.cpp
- Source/GUI/dvrescue/dvrescue/AnalysePage.qml
- Source/GUI/dvrescue/dvrescue/datamodel.cpp
- Source/GUI/dvrescue/dvrescue/datamodel.h
- Source/GUI/dvrescue/dvrescue/mediaplayer.cpp
- Source/GUI/dvrescue/dvrescue/mediaplayer.h
- Source/GUI/dvrescue/dvrescue/qt512/SplitView/SplitView.qml
- Source/GUI/dvrescue/dvrescue/qt513+/SplitView/SplitView.qml
- Source/GUI/dvrescue/dvrescue/xmlparser.cpp
- Source/GUI/dvrescue/dvrescue/xmlparser.h
https://github.com/mipops/dvrescue/issues/538
> Introduce more precise way of ms <=> frame index conversion

- Source/GUI/dvrescue/dvrescue/CaptureView.qml
> make highlight for selected deck more obvious

- tools/dvpackager
Search for FFmpeg and MediaInfo versions installed by GUI (linux only) prior to using system installed version.
> search for GUI installed dependencies (linux)

- Source/GUI/dvrescue/dvrescue/main.qml
resolves https://github.com/mipops/dvrescue/issues/530, thx @libbyhopfauf
> add an action to the help url

- Source/GUI/dvrescue/dvrescue/DvRescueLogo.ui.qml
new logo is square
fixes https://github.com/mipops/dvrescue/issues/277
> fix logo aspect ratio

- Source/GUI/dvrescue/dvrescue/PackagePage.qml
- Source/GUI/dvrescue/dvrescue/fileutils.cpp
- Source/GUI/dvrescue/dvrescue/fileutils.h
Otherwise open FolderDialog before packaging
> PackagePage: check if output directory is writable

- tools/dvplay
partly addresses https://github.com/mipops/dvrescue/issues/552
> Dvplay html updates

- .github/workflows/dvrescue-gui.yml
should fix CI issues. Once again.
> switch to ffmpeg5 builds cause ffmpeg4 seems to be not produced anymore

- Source/GUI/dvrescue/dvrescue/AnalysePage.qml
Fix https://github.com/mipops/dvrescue/issues/575.
> AnalysePage: Try to get permissions on the containing folder if needed

- Source/GUI/dvrescue/dvrescue/AnalysePage.qml
- Source/GUI/dvrescue/dvrescue/PackagePage.qml
- Source/GUI/dvrescue/dvrescue/dvrescue.pri
- Source/GUI/dvrescue/dvrescue/fileutils.cpp
- Source/GUI/dvrescue/dvrescue/fileutils.h
- Source/GUI/dvrescue/dvrescue/machelpers.h
- Source/GUI/dvrescue/dvrescue/machelpers.mm
+ Check permissions when opening file in PackagePage
> Show info message when prompting for permissions

- Source/GUI/dvrescue/dvrescue/AnalysePage.qml
- Source/GUI/dvrescue/dvrescue/PackagePage.qml
Fix https://github.com/mipops/dvrescue/issues/585.
> Check permissions when opening recent file

- Source/GUI/dvrescue/dvrescue/DvRescueCLI.qml
removing this output until it can be made available as an advanced option
> disable vtt output by default

- tools/dvpackager
responds to ^M issue in https://github.com/mipops/dvrescue/issues/594#issuecomment-1273696516
> set additional variables as arrays

- Source/GUI/dvrescue/dvrescue/AnalysePage.qml
- Source/GUI/dvrescue/dvrescue/DvLoupeCtl.qml
- Source/GUI/dvrescue/dvrescue/DvPackagerCtl.qml
- Source/GUI/dvrescue/dvrescue/DvPlayCtl.qml
- Source/GUI/dvrescue/dvrescue/SegmentDataViewWithToolbar.qml
- Source/GUI/dvrescue/dvrescue/main.cpp
Fix https://github.com/mipops/dvrescue/issues/594.
> Handle spaces in application directory path

- Source/Common/Merge.cpp
The last frame was not logged nor stored in that case:
```
93   3064 00:00:03;03 X PM  861    0 block picks &  579 remaining block errors
94   3071 00:00:00:01 0  M
```
> Fix last frames not outputted during merge if it has discontinuity and present in 1 take only

- Source/GUI/dvrescue/dvrescue.qmltests/dvrescue.qmltests.pro
- Source/GUI/dvrescue/dvrescue.qmltests/tests/tst_settings.qml
- Source/GUI/dvrescue/dvrescue/AnalyseDataView.qml
- Source/GUI/dvrescue/dvrescue/AnalysePage.qml
- Source/GUI/dvrescue/dvrescue/DvRescueCLI.qml
- Source/GUI/dvrescue/dvrescue/TableViewEx.qml
- Source/GUI/dvrescue/dvrescue/ToolsDialog.qml
- Source/GUI/dvrescue/dvrescue/main.qml
This is an edit of https://github.com/mipops/dvrescue/pull/595 to remove the options that aren't merged yet.
> Setting panel partial

- Source/Common/ProcessFile.cpp
> Fix rew command behavior in dvrescue

- Source/Common/Core.cpp
- Source/Common/ProcessFile.cpp
- Source/Common/ProcessFile.h
Depends on MediaArea/MediaInfoLib#1622
Snapshot: https://mediaarea.net/download/snapshots/binary/dvrescue/20221123-2/
> Handle user interruption (ctrl-c)

- Source/CLI/CLI_Help.cpp
- Source/CLI/CommandLine_Parser.cpp
- Source/Common/AvfCtl.h
- Source/Common/AvfCtl.m
- Source/Common/AvfCtlWrapper.h
- Source/Common/AvfCtlWrapper.mm
- Source/Common/Merge.cpp
- Source/Common/Merge.h
- Source/Common/ProcessFile.cpp
- Source/Common/ProcessFileWrapper.h
- Source/Common/SimulatorWrapper.cpp
- Source/Common/SimulatorWrapper.h
- tools/avfctl/main.m
> Allow --timeout option also for devices

- Source/Common/AvfCtl.h
- Source/Common/AvfCtl.m
- Source/Common/AvfCtlWrapper.h
- Source/Common/AvfCtlWrapper.mm
- Source/Common/Output_Xml.cpp
- Source/Common/ProcessFile.cpp
- Source/Common/ProcessFile.h
- Source/Common/ProcessFileWrapper.h
- Source/Common/SimulatorWrapper.cpp
- Source/Common/SimulatorWrapper.h
- tools/dvrescue.xsd
> Add partial capture info to xml

- .github/workflows/DVRescue_Checks.yml
- .github/workflows/dvrescue-gui.yml
- Project/GNU/CLI/AddThisToRoot_CLI_compile.sh
- Project/GNU/CLI/Makefile.am
- Project/GNU/CLI/configure.ac
- Project/GNU/dvrescue.dsc
- Project/GNU/dvrescue.spec
- Project/OBS/deb10.debian/control
- Project/OBS/deb10.dsc
- Project/OBS/deb11.debian/control
- Project/OBS/deb11.dsc
- Source/Common/LinuxWrapper.cpp
- Source/Common/LinuxWrapper.h
- Source/Common/ProcessFile.cpp
- Source/Common/ProcessFile.h
- debian/control
Snapshot: https://mediaarea.net/download/snapshots/binary/dvrescue/20221128-5/
> Capture support for Linux

- Project/GNU/GUI/AddThisToRoot_GUI_compile.sh
- Project/GNU/dvrescue.spec
- Project/OBS/deb10.debian/control
- Project/OBS/deb10.debian/rules
- Project/OBS/deb10.dsc
- Project/OBS/deb11.debian/control
- Project/OBS/deb11.debian/rules
- Project/OBS/deb11.dsc
> Add libfreetype to ffmpeg build

- Source/Common/LinuxWrapper.cpp
- Source/Common/LinuxWrapper.h
- Source/Common/ProcessFile.cpp
> Linux: Support capture by device UUID

- Source/Common/LinuxWrapper.cpp
- Source/Common/LinuxWrapper.h
> Bufferize capture on Linux

- .github/workflows/dvrescue-gui.yml
- Source/GUI/dvrescue/dvrescue/AnalyseFileView.qml
- Source/GUI/dvrescue/dvrescue/AnalysePage.qml
- Source/GUI/dvrescue/dvrescue/DvLoupeCtl.qml
- Source/GUI/dvrescue/dvrescue/DvPackagerCtl.qml
- Source/GUI/dvrescue/dvrescue/DvPlayCtl.qml
- Source/GUI/dvrescue/dvrescue/DvRescueCLI.qml
- Source/GUI/dvrescue/dvrescue/FilesModel.qml
- Source/GUI/dvrescue/dvrescue/MediaInfoModel.qml
- Source/GUI/dvrescue/dvrescue/PackageFileView.qml
- Source/GUI/dvrescue/dvrescue/PackageOutputFileView.qml
- Source/GUI/dvrescue/dvrescue/PackagePage.qml
- Source/GUI/dvrescue/dvrescue/ProgressTextDelegate.qml
- Source/GUI/dvrescue/dvrescue/RecentsPopup.qml
- Source/GUI/dvrescue/dvrescue/SegmentDataViewWithToolbar.qml
- Source/GUI/dvrescue/dvrescue/datamodel.cpp
- Source/GUI/dvrescue/dvrescue/main.cpp
- Source/GUI/dvrescue/dvrescue/main.qml
- Source/GUI/dvrescue/dvrescue/mediainfo.cpp
- Source/GUI/dvrescue/dvrescue/mediainfo.h
should also address https://github.com/mipops/dvrescue/issues/640
> dvpackager GUI: design layout adjustments (#661)

- Source/GUI/dvrescue/dvrescue-QtAVPlayer-lib/src/QtAVPlayer/QtAVPlayerLib.pro
- Source/GUI/dvrescue/dvrescue/mediaplayer.cpp
> Revert "update QtAVPlayer & adjust code"

- Project/GNU/CLI/Makefile.am
- Project/GNU/CLI/configure.ac
- Source/Common/DecklinkWrapper.cpp
- Source/Common/DecklinkWrapper.h
- Source/Common/Output_Mkv.cpp
- Source/Common/Output_Mkv.h
- Source/Common/ProcessFile.cpp
Fix #700 , fix #698
Currently only the merge option is supported
> Enable capture from Blackmagic DeckLink interface

- Project/GNU/CLI/Makefile.am
- Project/GNU/CLI/configure.ac
- Source/CLI/CLI_Help.cpp
- Source/CLI/CommandLine_Parser.cpp
- Source/Common/AvfCtl.h
- Source/Common/AvfCtl.m
- Source/Common/AvfCtlWrapper.h
- Source/Common/AvfCtlWrapper.mm
- Source/Common/DecklinkWrapper.cpp
- Source/Common/DecklinkWrapper.h
- Source/Common/Merge.h
- Source/Common/ProcessFile.cpp
- Source/Common/ProcessFile.h
- Source/Common/ProcessFileWrapper.cpp
- Source/Common/ProcessFileWrapper.h
- Source/Common/Sony9PinWrapper.cpp
- Source/Common/Sony9PinWrapper.h
- Source/ThirdParty/serial/LICENSE
- Source/ThirdParty/serial/include/serial/impl/unix.h
- Source/ThirdParty/serial/include/serial/impl/win.h
- Source/ThirdParty/serial/include/serial/serial.h
- Source/ThirdParty/serial/include/serial/v8stdint.h
- Source/ThirdParty/serial/src/impl/list_ports/list_ports_linux.cc
- Source/ThirdParty/serial/src/impl/list_ports/list_ports_osx.cc
- Source/ThirdParty/serial/src/impl/list_ports/list_ports_win.cc
- Source/ThirdParty/serial/src/impl/unix.cc
- Source/ThirdParty/serial/src/impl/win.cc
- Source/ThirdParty/serial/src/serial.cc
- tools/avfctl/main.m
Allows --cmd options with decklink devices
Add --control and --list_controls options
Fixes #699 
Fixes #708
> Add camera control support through Sony9Pin or DeckLink native interface

- Source/Common/ProcessFile.cpp
> Print error if control port cannot be opened

- Source/Common/ProcessFile.cpp
> Decklinc: fix typo

- Source/Common/ProcessFile.cpp
Snapshot [CLI](https://mediaarea.net/download/snapshots/binary/dvrescue/20231010), [GUI](https://mediaarea.net/download/snapshots/binary/dvrescue-gui/20231010)
> Try to remove unwanted spaces in JSON output

- Project/GNU/GUI/AddThisToRoot_GUI_compile.sh
> Update GUI build script

- Source/GUI/dvrescue/dvrescue/ToolsDialog.qml
- Source/GUI/dvrescue/dvrescue/main.qml
https://github.com/mipops/dvrescue/issues/565
> Expand Settings panel

- tools/dvpackager
fixes https://github.com/mipops/dvrescue/issues/695
> Dependency check

- Source/Common/Core.cpp
Snapshot: https://mediaarea.net/download/snapshots/binary/dvrescue/20231130/
> Handle SIGPIPE signal

- Source/Common/ProcessFile.cpp
> Autoselect first found device with --capture -- or --merge option

- Source/GUI/dvrescue/dvrescue/PlayerView.qml
- Source/GUI/dvrescue/dvrescue/fileutils.cpp
- Source/GUI/dvrescue/dvrescue/fileutils.h
- Source/GUI/dvrescue/dvrescue/mediaplayer.cpp
- Source/GUI/dvrescue/dvrescue/mediaplayer.h
> add cc filter

- Source/CLI/CommandLine_Parser.cpp
> Fix duplicated error message

- Project/GNU/CLI/test/captions.txt
- Source/Common/Core.cpp
- Source/Common/Output_Captions_Decode.cpp
- Source/Common/Output_Captions_Decode.h
- Source/Common/ProcessFile.cpp
- Source/Common/ProcessFile.h
SRT timestamps became broken at some point, fixing that.
Fix https://github.com/mipops/dvrescue/issues/789.
> Fix SRT timestamps

- Source/GUI/dvrescue/dvrescue/CapturePage.qml
- Source/GUI/dvrescue/dvrescue/DvRescueCLI.qml
https://github.com/mipops/dvrescue/issues/746
> better logging

- .github/workflows/dvrescue-gui.yml
- Source/Common/DecklinkWrapper.cpp
- Source/Common/DecklinkWrapper.h
- Source/Common/Output_Xml.cpp
- Source/Common/ProcessFile.cpp
- Source/Common/ProcessFile.h
- tools/dvrescue.xsd
> XML output for DeckLink capture

- .github/workflows/dvrescue-gui.yml
- Source/Common/LinuxWrapper.cpp
supersedes https://github.com/mipops/dvrescue/pull/832
> Linux capture rebased

- Source/Common/Output_Xml.cpp
- Source/Common/ProcessFileWrapper.cpp
- Source/Common/ProcessFileWrapper.h
- Source/ThirdParty/TimeCode/TimeCode.cpp
+ add tc_r and tc_nc to DeckLink XML
Fixes #767
> Add --csv support with decklink input

- tools/dvpackager
fixes https://github.com/mipops/dvrescue/issues/759
> increasing probesize with dv inputs in several spots

- .github/workflows/DVRescue_Checks.yml
- .github/workflows/dvrescue-gui.yml
- Source/Common/SimulatorWrapper.cpp
> Fix mutex unlock at bad level in SimulatorWrapper.cpp

- Source/Common/LinuxWrapper.cpp
- Source/Common/LinuxWrapper.h
> LinuxCapture: Add mutex around AVC calls

- Source/ThirdParty/ccdecoder/ccdecoder_line21field.c
Fix https://github.com/mipops/dvrescue/issues/844
> Fix 608 decoder about Roll-Up Captions

- Source/Common/Merge.cpp
Fixes #839
Snapshot: https://mediaarea.net/download/snapshots/binary/dvrescue/20240523-2
> Fix frame speed detection

- .github/workflows/dvrescue-gui.yml
- Source/Common/Core.cpp
- Source/Common/ProcessFile.cpp
- Source/Common/ProcessFile.h
> Print error if not device found or failed initialization

- Source/Common/ProcessFile.cpp
> Print message if no device with --list_devices or --list_controls

- Source/Common/ProcessFile.cpp
> Fix missing return code

- Source/Common/Output_Mkv.cpp
> Fix timecode range in matroska output

- Source/Common/DecklinkWrapper.cpp
> DeckLink: Give more time before querying status

- Project/Mac/Helpers.entitlements
- Project/Mac/mkdmg.sh
- Source/Common/DecklinkWrapper.cpp
- Source/GUI/dvrescue/dvrescue/CapturePage.qml
- Source/GUI/dvrescue/dvrescue/dvrescue.entitlements
Fixes #841
Untested, please test **from GUI**
[Snapshot](https://mediaarea.net/download/snapshots/binary/dvrescue-gui/20240609)
> Add macOS permissions for USB-Serial and DeckLink devices

- Source/GUI/dvrescue/dvrescue.qmltests/tests/tst_mergepage.qml
- Source/GUI/dvrescue/dvrescue/DvRescueCLI.qml
- Source/GUI/dvrescue/dvrescue/ToolsDialog.qml
- Source/GUI/dvrescue/dvrescue/main.qml
as it disables the csv communication between cli and gui
> remove --merge-log option

- Source/GUI/dvrescue/dvrescue.tests/xmlparsingtest.cpp
- Source/GUI/dvrescue/dvrescue.tests/xmlparsingtest.h
- Source/GUI/dvrescue/dvrescue/xmlparser.cpp
<stop> element should not prevent parsing of frames anymore
> analysis GUI blank until forced to generate new xml #869

- Source/Common/Merge.cpp
partly fixes https://github.com/mipops/dvrescue/issues/916
> fix typo in filenames

- Source/Common/Core.cpp
> Ensure terminate signal is handled in main thread

- Project/GNU/CLI/configure.ac
> Enable large file support

- docs/README.md
- docs/_sections/capture.md
- docs/css/main.css
Update capture.md to format numbered list and add note block in GUI Instructions section.
> format numbered list and add note block

- Source/Common/AvfCtl.m
> AvfCtl: Use IOkit to control devices

- Source/Common/Output.cpp
- Source/Common/Output.h
- Source/Common/Output_Xml.cpp
- Source/Common/ProcessFile.cpp
Needs https://github.com/MediaArea/MediaInfoLib/pull/2170
> DAT support
