mipops/dvrescue

- tools/dvrescue.xsd
The xsd in the add-some-tools branch at https://github.com/mipops/dvrescue/blob/add-some-scripts/tools/dvrescue.xsd covers the current (today) output of dvrescue. This PR includes proposes and considerations for subsequent refinement of the xml output of dvrescue. This includes:
- adding more attributes to frames
- presuming that if frame elements are reported with frames than the first and last will be include (or is the frame sequence duration as a frames attribute feasible?)
- adding a structure for audio errors
- starting to play with default attributes (like mkv elements with defaults) to anticipate reducing the data rate of the xml and aiding in reverse compatibility)
- adding @n_even as a compliement to @n which can be used to infer the cause of the error (tape vs deck)
> Schema updates

- Source/Common/Output.cpp
- Source/Common/ProcessFile.cpp
After https://github.com/mipops/dvrescue/pull/59, `int` max value is easily hit then there is a an `int` overflow.
Fix crash when relatively big files in input.
At the same time handle timestamps >= 100 hours (I am sure someone will try that one day :) ).
> Fix an int overflow in seconds_to_timestamp()

- tools/avfctl/main.m
With this pr update, the output of `./avfctl -h` is:
```
avfctl - control and capture from DV tape players via AVFoundation
version 0.19.11
Usage: avfctl [Options...] [OutputFile]
Options:
-h
Show this help and exit.
-list_devices
List detected devices and their indices.
-device <arg>
Specify the device to send commands to. <arg> is required and is the index of the device as shown in -list_devices.
If not specified, device with the index "0" is used by default.
-cmd <arg>
play      Set speed to 1.0 and mode to play.
stop      Set speed to 0.0 and mode to no-play.
rew       Set speed to -2.0 and mode to no-play.
ff        Set speed to 2.0 and mode to no-play.
capture   Set speed to 1.0 and mode to play and capture all raw-data and save to [OutputFile].
If [OutputFile] is not specified, …
```
> update help doc for avfctl

- tools/dvpackager
adds two new options for dvpackager
- `-e [mov|mkv]` to set the output format (mkv, mov, currently)
- `-S [Y|N]` to enable a subtitle track in the output of technical metadata
> dvpackager options

- Source/Common/Output_Xml.cpp
- Source/Common/ProcessFile.cpp
Resolves #66.
Needs https://github.com/MediaArea/MediaInfoLib/pull/1261.
~~~
<frames count="1" pts="00:00:00.000000" end_pts="00:00:00.033367" size="720x480" video_rate="30000/1001" chroma_subsampling="4:1:1" aspect_ratio="4/3" audio_rate="48000" channels="2" captions="y">
<frame n="0" pts="00:00:00.000000" tc="00:00:47;05" arb="F" caption-parity="mismatch">
~~~
> Information about caption presence in XML output

- Source/Common/Output_Xml.cpp
- tools/dvrescue.xsd
bumping the version since not using the captions attribute implies the default of 'n', as in that there are no captions, whereas before 1.1, the lack of the attribute had no implied meaning about captions
To be merged after https://github.com/mipops/dvrescue/pull/87
> add caption data to dvrescue xml schema

- Source/Common/Output.cpp
- Source/Common/Output.h
There was an issue in the API between MediaInfoLib and DVRescue, now using the fixed MediaInfoLib API. Not compatible with MediaInfoLib builds before https://github.com/MediaArea/MediaInfoLib/pull/1322.
> Fix recdate issues when days >=16

- tools/dvrescue2csv
@ElderOrb, this script lists the xpaths to fill various columns of a table presentation of a dvrescue report. Running `dvrescue2csv file.dv.dvrescue.xml` will make a csv of that information for now. I used a hack of concat and substring functions as an xpath version of if/else, but those use info about the frame to understand the block count per frame in order to show the video and audio error values as percentages rather than counts.
@ablwr this is similar to the table in your design document, but adds various other technical values, though I should probably reduce the booleans into more readable expressions.
> dvrescue2csv initial commit

- Source/Common/Output_Xml.cpp
Fix https://github.com/mipops/dvrescue/issues/193.
> if frames/@captions='p' then require first frame to use the caption attribute

- tools/dvrescue.xsd
fixes the xsd to match https://github.com/mipops/dvrescue/blob/b9d3f24099245952e53d7691eff57484b5d8da95/Source/Common/Output.h#L87
> fix typo in attribute name

- tools/dvpackager
When Homebrew is not installed, dvpackager ends up defining ```${BREW_PREFIX}``` as an empty string. This causes ```${BREW_PREFIX}/bin``` to become ```/bin```, making dvpackager look for FFmpeg at ```/bin/ffmpeg-dl```. This means that dvpackager never gets to look for FFmpeg using ```$(which ffmpeg)```.
This PR adds a check to ensure ```${BREW_PREFIX}``` is not empty before looking for FFmpeg at ```${BREW_PREFIX}/bin/ffmpeg-dl```, allowing dvpackager to use ```$(which ffmpeg)``` if Homebrew is not installed.
> Fix dvpackager FFmpeg detection when Homebrew is not installed

- Source/CLI/CLI_Help.cpp
- Source/CLI/CommandLine_Parser.cpp
- Source/Common/ProcessFile.cpp
Include time out limit for the pipe input after https://github.com/MediaArea/MediaInfoLib/pull/1379 is merged.
> Library options available from DVRescue command line

- Source/CLI/CommandLine_Parser.cpp
- Source/Common/Merge.cpp
- Source/Common/Merge.h
(Note: early stage, use it only as a proof of concept)
Option ` --use-abst y` to be used during merge of 2 files.
Without the new option, time code sync is wrong (begin of second file is synced with the first frames of first file having the same time code), abst mismatch seen.
With the option, time code sync is good (begin of second file is synced with the the second part of first frame).
```
dvrescue BCD00217_take2_54000000_Frame0-97.dv BCD00217_take1_54000000_Frame94-97.dv -m a.dv --verbosity 9 --use-abst n
#|Abst  |HH:MM:SS:FF|U|St|Comments
0   3480 00:00:00;00 X PM, 1331    0 block picks &  109 remaining block errors
1 ?????? 00:00:00;01 0   , abst   3495   3071
2 ?????? 00:00:00;02 0   , abst   3510   3086
3 ?????? 00:00:00;03 0  P, abst   3525   3101
4 ?????? 00:00:00;04 0  P, abst …
```
> Use abst as a hint for timecode sync, proof of concept

- Source/Common/Merge.cpp
Add a BlockErrors_Even column with block errors having an even Dseq number.
Resolve https://github.com/mipops/dvrescue/issues/503.
> CSV BlockErrors_Even

- Source/GUI/dvrescue/dvrescue/icons/alert-non-continuous-jump-ahead.svg
- Source/GUI/dvrescue/dvrescue/icons/alert-non-continuous-jump-back.svg
Here are new icons for "alert-non-continuous-jump" to indicate if the jump is forwards (ahead) or backward (back).
> new icons for non-continuous jump

- Source/Common/Output.cpp
- Source/Common/Output.h
- Source/Common/Output_Xml.cpp
- Source/Common/ProcessFile.cpp
- tools/dvrescue.xsd
with e.g. fastForwardPauseRewind.dv.
Before:
```
<frames count="698" pts="00:00:00.000000" end_pts="00:00:23.289933" size="720x480" video_rate="30000/1001" chroma_subsampling="4:1:1" aspect_ratio="4/3" captions="p">
<frames count="104" pts="00:00:23.289933" end_pts="00:00:26.760066" size="720x480" video_rate="30000/1001" chroma_subsampling="4:1:1" aspect_ratio="4/3" audio_rate="32000" channels="4">
```
After:
```
<frames count="107" pts="00:00:00.000000" end_pts="00:00:03.570233" size="720x480" video_rate="30000/1001" chroma_subsampling="4:1:1" aspect_ratio="4/3">
<frames count="2" pts="00:00:03.570233" end_pts="00:00:03.636966" size="720x480" video_rate="30000/1001" chroma_subsampling="4:1:1" aspect_ratio="4/3" speed="49">
<frames count="151" pts="00:00:03.636966" …
```
> Add DV speed in XML output, split frames element by DV speed

- Source/CLI/CommandLine_Parser.cpp
- Source/Common/Core.cpp
- Source/Common/Merge.cpp
- Source/Common/Merge.h
- Source/Common/ProcessFile.cpp
- Source/GUI/dvrescue/dvrescue/DvRescueCLI.qml
CLI with interactive mode if file exists, and `-n`/`-y` options for overriding it.
GUI (no risk to swap file names with it, but still a risk of unexpected overwrite) with `-y`, @g-maxime can we check if files exists and ask if writing is fine directly in the GUI?
For XML, WebVTT, log, merge outputs.
Fix https://github.com/mipops/dvrescue/issues/559.
> Check if file exists before overwriting

- tools/dvpackager
Avoid it to be evaluated to \0177 (on some bash versions?)
> dvpackager: declare STARTMESSAGE as array

- Source/Common/Merge.cpp
In the case of e.g. pipe and ingest is stopped in the middle of a frame, or if a file size is not a multiple of 120000, output is filled with garbage up to a multiple of 120000.
This patch removes such garbage data in output, and store last frame with only blocks available.
> Do not store garbage data if partial frame received

- Source/Common/Merge.cpp
Fix https://github.com/mipops/dvrescue/issues/592.
Verbosity <= 5:
```
DVRescue v.0.21.11 (MediaInfoLib v.22.06) by MIPoPS
20 frames in total.
[...]
```
(no change)
Verbosity > 5:
```
DVRescue v.0.21.11 (MediaInfoLib v.22.06) by MIPoPS
File 0: device://3
#|Abst  |HH:MM:SS:FF|U|S|Comments
0  12030 00:00:40;03 0   (     5 frames)
[...]
15  12180 00:00:40;18 0   (     5 frames)
20 frames in total.
[...]
```
(comments between 1st line and columns removed)
> Remove description of columns in text merge stats

- Source/Common/Merge.cpp
- Source/Common/Output_Xml.cpp
So XML during capture is (at least it is the goal) same as XML on the stored file.
Same file name, same size, in both XMLs.
> Use output file name and size for XML report during capture

- Source/CLI/CommandLine_Parser.cpp
- Source/Common/AvfCtl.h
- Source/Common/AvfCtl.m
- Source/Common/AvfCtlWrapper.h
- Source/Common/AvfCtlWrapper.mm
- Source/Common/Merge.h
- Source/Common/ProcessFile.cpp
- tools/avfctl/main.m
Example:
```
% ./dvrescue -list_devices             
0x80880503631782: GR-D70 (JVC GR-D70)
% ./dvrescue device://0x80880503631782
...
```
Snapshot: https://mediaarea.net/download/snapshots/binary/dvrescue/20221124/dvrescue_CLI_0.21.11.20221124_Mac.dmg
> Allow to use AVDevice uniqueID instead of device index

- .github/workflows/DVRescue_Checks.yml
- .github/workflows/dvrescue-gui.yml
+ Proposal to use install-qt-action to pin to Qt 6.2 on macOS
> Fix some ci errors

- Project/Mac/CLI.entitlements
- Project/Mac/mkdmg.sh
Fixes #715 
Please test [this snapshot](https://mediaarea.net/download/snapshots/binary/dvrescue/20230716/dvrescue_CLI_0.21.11.20230716_Mac.dmg)
> macOS CLI: Allow loading of external decklink library

- Source/CLI/CommandLine_Parser.cpp
- Source/Common/Merge.cpp
- Source/Common/Merge.h
- Source/Common/Output.h
- Source/Common/Output_Xml.cpp
- Source/Common/ProcessFile.cpp
Fix https://github.com/mipops/dvrescue/issues/603.
Needs https://github.com/MediaArea/MediaInfoLib/pull/1606.
> [WIP] Do not output synthetic gray/silence frames at begin/end

- tools/dvplay
I changed the colors to replace red and green (we use those a lot for symbolizing "good" vs. "bad" or warnings) with orange and pink. I also changed the shade of purple so the contrast was more noticeable in this order to make it more ADA friendly.
> Update dvplay color coding

- Source/GUI/dvrescue/dvrescue/mediaplayer.cpp
Fixes #838, Fixes #840 
Snapshot https://mediaarea.net/download/snapshots/binary/dvrescue-gui/20240406-2/dvrescue_GUI_22.12.20240406_Mac.dmg
> GUI: fix double-free on capture stop/application exit

- Source/GUI/dvrescue/dvrescue/DvRescueCLI.qml
workaround until https://github.com/mipops/dvrescue/issues/811 is resolved, else there's a chance that the xml and scc are out of sync with the output
> drop simultaneous scc and xml during capture

- Source/GUI/dvrescue/dvrescue/icons/package-alert-output-warning.svg
- Source/GUI/dvrescue/dvrescue/icons/package-error-audio-video-duration-mismatch.svg
- Source/GUI/dvrescue/dvrescue/icons/package-error-ffmpeg-error.svg
- Source/GUI/dvrescue/dvrescue/icons/package-error-input-output-framecount-mismatch.svg
Here are the new alert icons for packager. The yellow triangle (package-alert-output-warning) will be applied to files created in dvpackager that contain an issue/error. The corresponding icon for the specific error the file contains will appear next to the warning.
> new-package-alert-icons

- Source/GUI/dvrescue/dvrescue/windows-tools/scripts/dvrescue.sh
- Source/GUI/dvrescue/dvrescue/windows-tools/scripts/ffmpeg.sh
- Source/GUI/dvrescue/dvrescue/windows-tools/scripts/mediainfo.sh
- Source/GUI/dvrescue/dvrescue/windows-tools/scripts/xml.sh
> wrap ${args[@]} with quotes

- tools/dvpackager
This is a workaround for https://trac.ffmpeg.org/ticket/11339. This commit has dvpackager prefer the GUI-bundled ffmpeg which is pinned to a point before the regression in ffmpeg.
This should fix:
https://github.com/mipops/dvrescue/issues/950
https://github.com/mipops/dvrescue/issues/948
> prefer to use a gui-bundled ffmpeg

- Source/Common/Output_Xml.cpp
Use `full_conceal_aud` also for `r` & `l` values (`conceal_aud_value` was a typo, it is used for something else)
```
<frame n="131525" pos="778902092" pts="01:05:45.750000" abst="01:06:53:11" full_conceal_aud="l"/>
<frame n="131549" pos="778919558" pts="01:05:46.470000" abst="01:06:54:01" abst_r="1" full_conceal_aud="r"/>
<frame n="131550" pos="778925380" pts="01:05:46.500000" abst="01:06:54:01" abst_r="1" full_conceal_aud="1"/>
```
> DAT support, update

- tools/dvplay
- tools/dvsampler
This PR allows the environment variable `DVRESCUE_FONT` to set the font used by `dvplay` and `dvsampler`. This allows the font used to be configured by the user, and also allows a font to be provided so that the scripts can function properly when none of the hardcoded fonts could be found successfully.
Related-to: gh-974
> feat: allow setting `dvplay`/`dvsampler` font via envvar
